"""
Generates a SolidWorks VBA macro (.swb) file that creates a 3D hex-screw model.

Usage inside SolidWorks:
  Tools → Macro → Run → select the generated .swb file
"""

import math
import os
from screw_specs import circumscribed_radius


# ---------------------------------------------------------------------------
# VBA macro template
# ---------------------------------------------------------------------------
_MACRO_TEMPLATE = r"""' =============================================================
' SolidWorks VBA Macro — Hex Screw Generator
' Generated by: python hex_screw_generator
'
' Instructions:
'   1. Open SolidWorks.
'   2. Go to  Tools → Macro → Run.
'   3. Select this file ({filename}).
'   4. The macro creates a new Part with the hex screw geometry.
' =============================================================

Option Explicit

' ── SCREW PARAMETERS (all in METERS) ──────────────────────────────────────
Const NOM_DIA      As Double = {nom_dia_m}   ' Nominal shaft diameter
Const W_FLATS      As Double = {w_flats_m}   ' Width across flats
Const HEAD_HEIGHT  As Double = {head_h_m}    ' Head height
Const SHAFT_LENGTH As Double = {shaft_l_m}   ' Shaft length below head
Const TPI          As Integer = {tpi}         ' Threads per inch (for callout)
Const SCREW_LABEL  As String  = "{label}"

' Circumscribed hex radius (vertex → centre)
Const R_HEX As Double = {r_hex_m}

Sub main()
    Dim swApp     As SldWorks.SldWorks
    Dim swDoc     As SldWorks.ModelDoc2
    Dim swSkMgr   As SldWorks.SketchManager
    Dim swFtMgr   As SldWorks.FeatureManager
    Dim bRet      As Boolean
    Dim i         As Integer
    Dim pi        As Double : pi = 3.14159265358979

    Set swApp = Application.SldWorks

    ' ── Open new Part ──────────────────────────────────────────────────────
    Dim tmpl As String
    tmpl = swApp.GetUserPreferenceStringValue( _
               swUserPreferenceStringValue_e.swDefaultTemplatePart)
    Set swDoc  = swApp.NewDocument(tmpl, 0, 0, 0)
    Set swSkMgr = swDoc.SketchManager
    Set swFtMgr = swDoc.FeatureManager

    ' ── Step 1 : Hex-head profile on Top Plane ─────────────────────────────
    ' The head extrudes upward (+Z).  Shaft extrudes downward (−Z).
    bRet = swDoc.Extension.SelectByID2( _
               "Top Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
    swSkMgr.InsertSketch True
    swDoc.ClearSelection2 True

    ' Draw six lines forming a regular hexagon
    ' Flat-to-flat orientation: first vertex at 30 degrees
    Dim ang1 As Double, ang2 As Double
    Dim x1 As Double, y1 As Double, x2 As Double, y2 As Double
    For i = 0 To 5
        ang1 = (pi / 6) + i * (pi / 3)
        ang2 = (pi / 6) + (i + 1) * (pi / 3)
        x1 = R_HEX * Cos(ang1)
        y1 = R_HEX * Sin(ang1)
        x2 = R_HEX * Cos(ang2)
        y2 = R_HEX * Sin(ang2)
        swSkMgr.CreateLine x1, y1, 0, x2, y2, 0
    Next i

    ' Close sketch
    swSkMgr.InsertSketch True
    swDoc.ClearSelection2 True

    ' Extrude hex head UPWARD (flip = False)
    bRet = swDoc.Extension.SelectByID2( _
               "Sketch1", "SKETCH", 0, 0, 0, False, 4, Nothing, 0)
    swFtMgr.FeatureExtrusion2 _
        True, False, False, _      ' Single dir, no flip, dir flag N/A
        0, 0, _                    ' Blind, blind
        HEAD_HEIGHT, 0, _          ' Depth, depth2
        False, False, False, False, _
        0.0174533, 0.0174533, _
        False, False, False, _
        True, False, True           ' merge, useFeatScope=F, useAutoSelect=T
    swDoc.ClearSelection2 True

    ' ── Step 2 : Shaft circle on same Top Plane ────────────────────────────
    bRet = swDoc.Extension.SelectByID2( _
               "Top Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
    swSkMgr.InsertSketch True
    swDoc.ClearSelection2 True

    ' Circle centred at origin, radius = NOM_DIA / 2
    swSkMgr.CreateCircle 0, 0, 0, NOM_DIA / 2, 0, 0

    ' Close sketch
    swSkMgr.InsertSketch True
    swDoc.ClearSelection2 True

    ' Extrude shaft DOWNWARD (flip = True → negative Z)
    bRet = swDoc.Extension.SelectByID2( _
               "Sketch2", "SKETCH", 0, 0, 0, False, 4, Nothing, 0)
    swFtMgr.FeatureExtrusion2 _
        True, True, False, _       ' Single dir, FLIP = True (downward)
        0, 0, _
        SHAFT_LENGTH, 0, _
        False, False, False, False, _
        0.0174533, 0.0174533, _
        False, False, False, _
        True, False, True
    swDoc.ClearSelection2 True

    ' ── Step 3 : Chamfer at the screw tip (45°, small) ─────────────────────
    ' Selects the bottom circular edge of the shaft and applies chamfer.
    Dim chamfer As Double
    chamfer = NOM_DIA * 0.075     ' ~7.5% of diameter

    bRet = swDoc.Extension.SelectByID2( _
               "Edge<1>", "EDGE", 0, -(SHAFT_LENGTH), 0, False, 0, Nothing, 0)
    If bRet Then
        swFtMgr.InsertFeatureChamfer 4, 1, False, chamfer, 0.7854, 0, 0, 0
        swDoc.ClearSelection2 True
    End If

    ' ── Step 4 : Rename & set view ─────────────────────────────────────────
    swDoc.SetTitle2 SCREW_LABEL
    swDoc.ShowNamedView2 "*Isometric", -1
    swDoc.ViewZoomtofit2
    swDoc.GraphicsRedraw2

    MsgBox "Hex screw created successfully!" & Chr(10) & Chr(10) & _
           "  Label  : " & SCREW_LABEL & Chr(10) & _
           "  Shaft  : " & Format(SHAFT_LENGTH * 39.3701, "0.000") & Chr(34) & Chr(10) & _
           "  Head W : " & Format(W_FLATS * 39.3701, "0.000") & Chr(34) & " across flats" & Chr(10) & _
           "  Head H : " & Format(HEAD_HEIGHT * 39.3701, "0.000") & Chr(34), _
           vbInformation, "Hex Screw Generator"
End Sub
"""


def generate_macro(
    spec: dict,
    shaft_length_in: float = 1.0,
    output_dir: str = ".",
    filename: str | None = None,
) -> str:
    """
    Generate a SolidWorks VBA macro (.swb) for the given screw spec.

    Parameters
    ----------
    spec            : dict from screw_specs.get_spec()
    shaft_length_in : shaft length in inches (default 1.0")
    output_dir      : directory where the .swb file is written
    filename        : override the output filename (no extension needed)

    Returns
    -------
    Absolute path to the generated .swb file.
    """
    M = 0.0254  # inches → meters

    nom   = spec["nominal"]
    W     = spec["W"]
    H     = spec["H"]
    tpi   = spec["tpi"]
    frac  = spec["fraction"]
    R_hex = circumscribed_radius(W)

    label = f"{frac}-{tpi} UNC Hex Bolt  L={shaft_length_in}\""

    if filename is None:
        safe_frac = frac.replace("/", "_").replace("-", "_")
        filename = f"hex_screw_{safe_frac}_L{shaft_length_in}in.swb"
    elif not filename.endswith(".swb"):
        filename += ".swb"

    content = _MACRO_TEMPLATE.format(
        filename     = filename,
        nom_dia_m    = f"{nom * M:.8f}",
        w_flats_m    = f"{W * M:.8f}",
        head_h_m     = f"{H * M:.8f}",
        shaft_l_m    = f"{shaft_length_in * M:.8f}",
        r_hex_m      = f"{R_hex * M:.8f}",
        tpi          = tpi,
        label        = label,
    )

    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, filename)
    with open(path, "w") as fh:
        fh.write(content)

    return os.path.abspath(path)
